DELETE http://localhost:3001/api/reviews/6230ce1b172fb986c8c17a94
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjIyZGYwODA0NmIyNTIwZjVkMmFjODU0IiwiaWF0IjoxNjQ3Mjk3NDc0fQ.J6hv_JT2-Kq4Q3jgSYv7PAyQckFobhd8ek9vUrwWhCE